.github/workflows/label.yml
.github/workflows/release-please.yml

similar to https://github.com/google-github-actions/deploy-cloud-functions/pull/13/

chore: add label, remove old release config

---

.github/workflows/deploy-cloudrun-credentials-it.yml
.github/workflows/deploy-cloudrun-it.yml
.github/workflows/deploy-cloudrun.yml
.github/workflows/example-workflow-quickstart.yaml
.github/workflows/example-workflow.yaml
README.md
example-app/.dockerignore
example-app/Dockerfile
example-app/index.js
example-app/package-lock.json
example-app/package.json

feat: add example workflows

---

.github/workflows/deploy-cloudrun-credentials-it.yml
.github/workflows/deploy-cloudrun-it.yml
package.json
src/cloudRun.ts
src/index.ts
src/service.ts
tests/e2e.test.ts
tests/unit/service.namedrevision.yaml

fix: force update revision name

---

src/service.ts
tests/e2e.test.ts

fix: update merging of services

---

.github/workflows/deploy-cloudrun-traffic-it.yml
.github/workflows/deploy-cloudrun.yml
README.md
action.yml
example-app/Dockerfile
example-app/index.js
package.json
src/deploy-cloudrun.ts
tests/e2e.test.ts
tests/unit/deploy-cloudrun.test.ts

Fixes #16 - input field 'source'
Fixes #39 - input field 'suffix'

feat: Add source deploys and traffic updates

---

.github/workflows/deploy-cloudrun-credentials-it.yml
.github/workflows/deploy-cloudrun-it.yml
.github/workflows/deploy-cloudrun-traffic-it.yml

Reverts google-github-actions/deploy-cloudrun#68

Revert "fix: Update to PR target"

---

.github/workflows/deploy-cloudrun-it.yml
README.md
tests/unit/service.full.yaml

docs: fix metadata documentation

---

.github/workflows/deploy-cloudrun-credentials-it.yml
.github/workflows/deploy-cloudrun-traffic-it.yml
.github/workflows/example-workflow.yaml
README.md

Refs https://github.com/google-github-actions/setup-gcloud/issues/430

fix: update docs to list full job and pin auth to @v0

---

.github/workflows/deploy-cloudrun-it.yml

chore: don't fail on cleanup

---

.github/workflows/example-workflow-quickstart.yaml
.github/workflows/example-workflow.yaml
.github/workflows/tag.yml
README.md

Add workflow to tag floating aliases

---

README.md

Updating documentation to reflect recommendation of checking out the repo as first step, as per issue https://github.com/google-github-actions/deploy-cloudrun/issues/282

add actions/checkout@v2 as first step in documentation

---

src/deploy-cloudrun.ts
tests/unit/deploy-cloudrun.test.ts

feat: support single quote flags

---

package-lock.json
package.json

This should resolve issues where output is swallowed

chore: update to latest gcloud sdk

---

src/deploy-cloudrun.ts

Closes https://github.com/google-github-actions/deploy-cloudrun/pull/299

feat: allow for multi line flags

---

.github/workflows/deploy-cloudrun-credentials-it.yml
.github/workflows/deploy-cloudrun-it.yml
.github/workflows/deploy-cloudrun-traffic-it.yml
package-lock.json
package.json

fix: set output and update deps

---

.github/workflows/integration.yml

Add an integration test for labels

---

.github/workflows/cleanup.yml

Perform a checkout during the cleanup workflow

---

.github/workflows/integration.yml
README.md
package-lock.json
package.json
src/main.ts
tests/fixtures/job.yaml
tests/fixtures/service.yaml
tests/unit/main.test.ts

Closes https://github.com/google-github-actions/deploy-cloudrun/issues/508

Support jobs metadata too

---

README.md
action.yml

Closes #530
This doesn't remove the functionality or the tests.

docs: remove csv regions since it's not implemented upstream

---

README.md
action.yml
src/main.ts
tests/unit/main.test.ts

https://github.com/google-github-actions/deploy-cloudrun/issues/537#issuecomment-2302097605

Use separate flags for deploy and update-traffic commands
